<?php return array(
    'root' => array(
        'name' => 'pimcore/skeleton',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'amnuts/opcache-gui' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'a4af194185bcda734cf3e15e877b217153fffd2b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amnuts/opcache-gui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => '8674e51bb65af933a5ffaf1c308a660387c35c22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'behat/gherkin' => array(
            'pretty_version' => 'v4.9.0',
            'version' => '4.9.0.0',
            'reference' => '0bc8d1e30e96183e4f36db9dc79caead300beff4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cache/integration-tests' => array(
            'pretty_version' => '0.16.0',
            'version' => '0.16.0.0',
            'reference' => 'a8d9538a44ed5a70d551f9b87f534c98dfe6b0ee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cache/integration-tests',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cache/tag-interop' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'b062b1d735357da50edf8387f7a8696f3027d328',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cache/tag-interop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cbschuld/browser.php' => array(
            'pretty_version' => 'v1.9.6',
            'version' => '1.9.6.0',
            'reference' => '9d07d6410977d494d7b8ecc2f3c877645c5477d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cbschuld/browser.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeception/codeception' => array(
            'pretty_version' => '2.4.5',
            'version' => '2.4.5.0',
            'reference' => '5fee32d5c82791548931cbc34806b4de6aa1abfc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/codeception',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'pretty_version' => '7.8.4',
            'version' => '7.8.4.0',
            'reference' => 'dd44fc152433d27d3de03d59b4945449b3407af0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/phpunit-wrapper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/stub' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '853657f988942f7afb69becf3fd0059f192c705a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'colinmollenhour/credis' => array(
            'pretty_version' => 'v1.15.0',
            'version' => '1.15.0.0',
            'reference' => '28810439de1d9597b7ba11794ed9479fb6f3de7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../colinmollenhour/credis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.6',
            'version' => '1.3.6.0',
            'reference' => '90d087e988ff194065333d16bc5cf649872d9cdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'container-interop/container-interop' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '79cbf1341c22ec75643d841642dd5d6acd83bdb8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../container-interop/container-interop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'container-interop/container-interop-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.2',
            ),
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => '8e6b6ea76eabbf19ea2bf5b67b98e1860474012f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'defuse/php-encryption' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'f53396c2d34225064647a05ca76c1da9d99e5828',
            'type' => 'library',
            'install_path' => __DIR__ . '/../defuse/php-encryption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'reference' => 'fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'reference' => '56cd022adb5514472cb144c087393c1821911d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '2.13.3',
            'version' => '2.13.3.0',
            'reference' => 'f3812c026e557892c34ef37f6ab808a6b567da7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.12.1',
            'version' => '2.12.1.0',
            'reference' => 'adce7a954a1c2f14f85e94aed90c8489af204086',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '612a3ee5ab0d5dd97b7cf3874a6efe24325efac3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '1.12.13',
            'version' => '1.12.13.0',
            'reference' => '85460b85edd8f61a16ad311e7ffc5d255d3c937c',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-cache-bundle' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '6bee2f9b339847e8a984427353670bad4e7bdccb',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-cache-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-migrations-bundle' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => '49fa399181db4bf4f9f725126bd1cb65c4398dce',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-migrations-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.4',
            'version' => '1.4.4.0',
            'reference' => '4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => 'v1.8.1',
            'version' => '1.8.1.0',
            'reference' => '215438c0eef3e5f9b7da7d09c6b90756071b43e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'reference' => '7a6eac9fb6f61bba91328f15aa7547f4806ca288',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/reflection' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '6bcea3e81ab8b3d0abe5fde5300bbc8a968960c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/reflection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'reference' => '0dbf5d78455d4d6a41d186da50adc1122ec066f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '3.9.7',
            'version' => '3.9.7.0',
            'reference' => '94563d7b3105288e6ac53a67ae720e3669fac1f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facebook/webdriver' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'reference' => 'e43de70f3c7166169d0f14a374505392734160e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/webdriver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'reference' => '83b609028194aa042ea33b5af2d41a7427de80e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofphp/proxy-manager-lts' => array(
            'pretty_version' => 'v1.0.16',
            'version' => '1.0.16.0',
            'reference' => 'ecadbdc9052e4ad08c60c8a02268712e50427f7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../friendsofphp/proxy-manager-lts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofsymfony/jsrouting-bundle' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => 'c978fabc6a21a77052ff3fe927b41111ec944f0d',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../friendsofsymfony/jsrouting-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.13.0',
            'version' => '2.13.0.0',
            'reference' => '6a41d8fbd6b90052bc34dff3b4252d0f88067b23',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/apiclient' => array(
            'pretty_version' => 'v2.9.2',
            'version' => '2.9.2.0',
            'reference' => 'e9ef4c26a044b8d39a46bcf296be795fe24a1849',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/apiclient-services' => array(
            'pretty_version' => 'v0.181.0',
            'version' => '0.181.0.0',
            'reference' => 'a4ea5fd96887d654d10d446b239e1ff60240e2c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient-services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'f1f0d0319e2e7750ebfaa523c78819792a9ed9f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.8',
            'version' => '6.5.8.0',
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => '67ab6e18aaa14d753cc148911d273f6e6cb6721e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'e4490cabc77465aaee90b20cfc9a770f8c04be6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'html2text/html2text' => array(
            'pretty_version' => '4.3.1',
            'version' => '4.3.1.0',
            'reference' => '61ad68e934066a6f8df29a3d23a6460536d0855c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../html2text/html2text',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'http-interop/http-factory-guzzle' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '8f06e92b95405216b237521cc64c804dd44c4a81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../http-interop/http-factory-guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hybridauth/hybridauth' => array(
            'pretty_version' => 'v2.18.0',
            'version' => '2.18.0.0',
            'reference' => 'a879408ad340b68c79faeea2e7a85b95a1f261ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hybridauth/hybridauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jdorn/sql-formatter' => array(
            'pretty_version' => 'v1.2.17',
            'version' => '1.2.17.0',
            'reference' => '64990d96e0959dff8e059dfcdc1af130728d92bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jdorn/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'khanamiryan/qrcode-detector-decoder' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '45326fb83a2a375065dbb3a134b5b8a5872da569',
            'type' => 'library',
            'install_path' => __DIR__ . '/../khanamiryan/qrcode-detector-decoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'knplabs/knp-components' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'reference' => 'ab7ced8a662e6aa1898b5c4919fe3eb78d62d963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../knplabs/knp-components',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'knplabs/knp-paginator-bundle' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'reference' => 'ea6ac65818a734a9afaa05270e162506e726c184',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../knplabs/knp-paginator-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.3.0',
            'version' => '4.3.0.0',
            'reference' => '1beb4447f9efd26041eba7eff50614e798c353fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-eventmanager' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => '41f7209428f37cab9573365e361f4078209aaafa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-eventmanager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '3.4.6',
            'version' => '3.4.6.0',
            'reference' => '3ef8657a78278dfeae7707d51747251db4176240',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.8.0',
            'version' => '9.8.0.0',
            'reference' => '9d2e0265c5d90f5dd601bc65ff717e05cec19b47',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'linfo/linfo' => array(
            'pretty_version' => 'v4.0.7',
            'version' => '4.0.7.0',
            'reference' => 'b2719321a34cbbd3f87407649610d5fff3177d3f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../linfo/linfo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => '30ad6f93cf3efe4192bc7a4c9cad11ff8f4f237f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.11.0',
            'version' => '1.11.0.0',
            'reference' => 'b1f3c0699525336d09cc5161a2861268d9f2ae5b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.9.0',
            'version' => '0.9.0.0',
            'reference' => '4dc5a3e8df38aea4ca3b1096cee3a038094e9b53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mjaschen/phpgeo' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'reference' => '4b1c167dece6b0733bb5663f2e079a744dc36244',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mjaschen/phpgeo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.27.1',
            'version' => '1.27.1.0',
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpratt/embera' => array(
            'pretty_version' => '2.0.34',
            'version' => '2.0.34.0',
            'reference' => '7cee7dfd4e46cb45fd8f2f15195d90cf2442becc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpratt/embera',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mustangostang/spyc' => array(
            'pretty_version' => '0.6.3',
            'version' => '0.6.3.0',
            'reference' => '4627c838b16550b666d15aeae1e5289dd5b77da0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mustangostang/spyc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.1',
            'version' => '1.11.1.0',
            'reference' => '7284c22080590fb39f2ffa3e9057f10a4ddd0e0c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.4',
            'version' => '1.8.4.0',
            'reference' => 'a867478eae49c9f59ece437ae7f9506bfaa27483',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'c1fbe70bfb5ad41b8ec5785056b0e308b40d4831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.68.1',
            'version' => '2.68.1.0',
            'reference' => '4f991ed2a403c85efbc4f23eb4030063fdbe01da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ocramius/package-versions' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => 'f51ff2b2b49baaa302d6bf71880e4d8b5acd7015',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../ocramius/package-versions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ocramius/proxy-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.1',
            ),
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.6.3',
            'version' => '2.6.3.0',
            'reference' => '58c3f47f650c94ec05a151692652a868995d2938',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paypal/rest-api-sdk-php' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'reference' => '72e2f2466975bf128a31e02b15110180f059fc04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/rest-api-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '45a2ec53a73c70ce41d55cedef9063630abaf1b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phive/twig-extensions-deferred' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'reference' => '2d8514ef779e1e33724befed86be62cc3c23c405',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phive/twig-extensions-deferred',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.3.0',
            'version' => '5.3.0.0',
            'reference' => '622548b623e81ca6d78b721c5e029f4ce664f170',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'reference' => 'b2fe4d22a5426f38e014855322200b97b5362c0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'fde2ccf55eaef7e86021ff1acce26479160a0fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.21',
            'version' => '3.0.21.0',
            'reference' => '4580645d3fc05c189024eb3b834c6c1e4f0f30a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '15873c65b207b07765dbc3c95d20fdf4a320cbe2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.23.1',
            'version' => '1.23.1.0',
            'reference' => '846ae76eef31c6d7790fac9bc399ecee45160b26',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '6.1.4',
            'version' => '6.1.4.0',
            'reference' => '807e6013b00af69b6c5d9ceb4282d0393dbb9d8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => '42c5ba5220e6904cbfe8b1a1bda7c0cfdc8c12f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '2454ae1765516d20c4ffe103d85a58a9a3bd5662',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '3.1.3',
            'version' => '3.1.3.0',
            'reference' => '9c1da83261628cb24b6a6df371b6e312b3954768',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '7.5.20',
            'version' => '7.5.20.0',
            'reference' => '9467db479d1b0487c99733bb1e7944d32deded2c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'pimcore/pimcore' => array(
            'pretty_version' => 'v6.9.6',
            'version' => '6.9.6.0',
            'reference' => '9a33afacc268d9779bf6419639e8c208355e50c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimcore/pimcore',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pimcore/skeleton' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'piwik/device-detector' => array(
            'pretty_version' => '3.13.1',
            'version' => '3.13.1.0',
            'reference' => 'e90533302c58acf41f0d8075a0151537d0ddf34d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../piwik/device-detector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'presta/sitemap-bundle' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'fb83304ce365699b879cf7e998f1d5bbec8ddb27',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../presta/sitemap-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
                1 => '1.0',
            ),
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '0955afe48220520692d2d09f7ab7e0f93ffd6a31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/link' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'eea8e8662d5cd3ae4517c9b864493f59fca95562',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/link',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/link-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
                1 => '1.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '3.9.7',
            'version' => '3.9.7.0',
            'reference' => 'dc75aa439eb4c1b77f5379fd958b3dc0e6014178',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.9.7',
            ),
        ),
        'sabre/dav' => array(
            'pretty_version' => '3.2.3',
            'version' => '3.2.3.0',
            'reference' => 'a9780ce4f35560ecbd0af524ad32d9d2c8954b80',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/dav',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabre/event' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '831d586f5a442dceacdcf5e9c4c36a4db99a3534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/event',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabre/http' => array(
            'pretty_version' => 'v4.2.4',
            'version' => '4.2.4.0',
            'reference' => 'acccec4ba863959b2d10c1fa0fb902736c5c8956',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabre/uri' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'ada354d83579565949d80b2e15593c2371225e61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabre/vobject' => array(
            'pretty_version' => '4.2.2',
            'version' => '4.2.2.0',
            'reference' => '449616b2d45b95c8973975de23f34a3d14f63b4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/vobject',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabre/xml' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => 'a367665f1df614c3b8fefc30a54de7cd295e444e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/xml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'scheb/two-factor-bundle' => array(
            'pretty_version' => 'v3.29.0',
            'version' => '3.29.0.0',
            'reference' => 'c7a86475c2d2f77e84ac3375592cefb0c2ad924b',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../scheb/two-factor-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '1de8cd5c010cb153fcd68b8d0f64606f523f7619',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'reference' => '1dc7ceb4a24aede938c7af2a9ed1de09609ca770',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => '6296a0c086dd0117c1b78b059374d7fcbe7545ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '4.2.4',
            'version' => '4.2.4.0',
            'reference' => 'd47bbbad83711771f167c72d4e3f25f7fcc1f8b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '3.1.5',
            'version' => '3.1.5.0',
            'reference' => '73a9676f2833b9a7c36968f9d882589cd75511e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => 'e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '9b8772b9cbd456ab45d4a598d2dd1a1bced6363d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '367dcba38d6e1977be014dc4b22f47a484dac7fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '31d35ca87926450c44eae7e2611d45a7a65ea8b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sensio/framework-extra-bundle' => array(
            'pretty_version' => 'v5.6.1',
            'version' => '5.6.1.0',
            'reference' => '430d14c01836b77c28092883d195a43ce413ee32',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/framework-extra-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sensiolabs/ansi-to-html' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => '94a3145aae4733ff933c8910263ef56d1ae317a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sensiolabs/ansi-to-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sonata-project/google-authenticator' => array(
            'pretty_version' => '2.3.1',
            'version' => '2.3.1.0',
            'reference' => '71a4189228f93a9662574dc8c65e77ef55061b59',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sonata-project/google-authenticator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'reference' => '8a5d5072dca8f48460fce2f4131fcc495eec654c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony-cmf/routing' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'reference' => 'bbcdf2f6301d740454ba9ebb8adaefd436c36a6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony-cmf/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony-cmf/routing-bundle' => array(
            'pretty_version' => '2.5.1',
            'version' => '2.5.1.0',
            'reference' => 'e9c3dfb9815b68b7f95d18308ca036cccadd4739',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony-cmf/routing-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/amazon-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/asset' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/browser-kit' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/cache-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.13',
            ),
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/contracts' => array(
            'pretty_version' => 'v1.1.13',
            'version' => '1.1.13.0',
            'reference' => '9e27f5c175ecbd6fff554d839ff4a432da797168',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/debug' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/debug-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/dom-crawler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/dotenv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/error-handler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/event-dispatcher-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.13',
            ),
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1',
            ),
        ),
        'symfony/expression-language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/framework-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/google-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/http-client' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/http-client-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.13',
            ),
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'symfony/http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/http-kernel' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/inflector' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/intl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/ldap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/lock' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/mailchimp-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/mailgun-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/messenger' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/mime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/monolog-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/monolog-bundle' => array(
            'pretty_version' => 'v3.8.0',
            'version' => '3.8.0.0',
            'reference' => 'a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/monolog-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '927013f3aac555983a5059aada98e1907d842695',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-icu' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => 'a3d9148e2c363588e05abbdd4ee4f971f0a5330c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-icu',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '707403074c8ea6e2edaf8794b0157a0bfa52157a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/postmark-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/process' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/property-access' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/property-info' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/proxy-manager-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security-core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security-csrf' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security-guard' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/security-http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/sendgrid-mailer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/serializer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/service-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.13',
            ),
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/stopwatch' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/swiftmailer-bundle' => array(
            'pretty_version' => 'v3.5.4',
            'version' => '3.5.4.0',
            'reference' => '9daab339f226ac958192bf89836cb3378cc0e652',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/swiftmailer-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/symfony' => array(
            'pretty_version' => 'v4.4.50',
            'version' => '4.4.50.0',
            'reference' => '6bc1c2e2506327daa9a2359ec45f7098ca947728',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/symfony',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/templating' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/translation-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.13',
            ),
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/twig-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/twig-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/validator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/var-dumper' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/var-exporter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/web-link' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/web-profiler-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/web-server-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/workflow' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'symfony/yaml' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v4.4.50',
            ),
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => 'c42125b83a4fa63b187fdf29f9c93cb7733da30c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/extensions' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'reference' => '57873c8b0c1be51caa47df2cdb824490beb16202',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/extensions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v2.15.5',
            'version' => '2.15.5.0',
            'reference' => 'fc02a6af3eeb97c4bf5650debc76c2eda85ac22e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'umpirsky/country-list' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'reference' => '6dddae6983c1bc4d314b513c5decb7c8c6c879dc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../umpirsky/country-list',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vrana/adminer' => array(
            'pretty_version' => 'v4.8.1',
            'version' => '4.8.1.0',
            'reference' => '1f173e18bdf0be29182e0d67989df56eadea4754',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vrana/adminer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vrana/jush' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '6f4e94d7660f1d610347e3b7871b0617d1cf5557',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vrana/jush',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozarts/console-parallelization' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '671dc35f5a08911132dee037583d51cef1055766',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozarts/console-parallelization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'willdurand/jsonp-callback-validator' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'reference' => '1a7d388bb521959e612ef50c5c7b1691b097e909',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/jsonp-callback-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zendframework/zend-code' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.3.0',
            ),
        ),
        'zendframework/zend-paginator' => array(
            'pretty_version' => '2.8.2',
            'version' => '2.8.2.0',
            'reference' => '2b4d07d9475ed581278a28d065b238a0941402e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zendframework/zend-paginator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zendframework/zend-servicemanager' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'a1ed6140d0d3ee803fec96582593ed024950067b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zendframework/zend-servicemanager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zendframework/zend-stdlib' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '66536006722aff9e62d1b331025089b7ec71c065',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zendframework/zend-stdlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
